# Generated by Django 3.2.13 on 2023-12-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231212_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=0, primary_key='True', serialize=False),
        ),
    ]
